[project]
name = "nlp-projekt"
version = "0.1.0"
description = "AI agent for writing SQL queries based on natural language input."
authors = [
    { name = "Mikołaj Garbowski", email = "mikolaj.garbowski@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain[huggingface]>=1.2.15",
    "langchain-community>=0.4.1",
    "langgraph>=1.1.6",
    "ipykernel>=7.2.0",
    "transformers>=5.5.3",
    "torch>=2.11.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=9.0.3",
    "ruff>=0.15.10",
    "ty>=0.0.29",
]
